# Generated by Django 2.0.1 on 2018-06-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_manager', '0002_auto_20180609_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id_travel',
            field=models.CharField(default='', max_length=500),
        ),
    ]
