# Generated by Django 2.0.1 on 2018-06-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_manager', '0003_auto_20180609_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='id_user',
            field=models.CharField(default='', max_length=500),
        ),
    ]
